### ISSUE TITLE
Unsupported Array of Sympbol

### ISSUE THREAD

**Issue by joel** [railsconfig/config#100]
I don't know why but it's a fact : 

supported : 
```
supported: ['en', 'fr', 'fr_DJ', 'es'] 
```
unsupported : 

```
unsupported: %i(en fr fr_DJ es de it pt)
unsupported: <%= %i(en fr fr_DJ es de it pt) %>
unsupported: <%= ['en', 'fr', 'fr_DJ', 'es'].map(&:to_sym) %>
unsupported: [:en, :fr, :fr_DJ, :es, :de, :it, :pt]
unsupported: <%= [:en, :fr, :fr_DJ, :es, :de, :it, :pt] %>
```

env :
```
ruby '2.1.2'
gem 'rails', '4.1.9'
```

Stacktrace :  

```
Psych::SyntaxError: (<unknown>): did not find expected node content while parsing a flow node at line 7 column 17
```

```
from /Users/joel/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/psych.rb:370:in `parse_stream'
	from /Users/joel/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/psych.rb:318:in `parse'
	from /Users/joel/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/psych.rb:245:in `load'
	from /Users/joel/.rvm/gems/ruby-2.1.2@tonpsy/gems/rails_config-0.4.2/lib/rails_config/sources/yaml_source.rb:17:in `load'
	from /Users/joel/.rvm/gems/ruby-2.1.2@tonpsy/gems/rails_config-0.4.2/lib/rails_config/options.rb:40:in `block in reload!'
	from /Users/joel/.rvm/gems/ruby-2.1.2@tonpsy/gems/rails_config-0.4.2/lib/rails_config/options.rb:39:in `each'
	from /Users/joel/.rvm/gems/ruby-2.1.2@tonpsy/gems/rails_config-0.4.2/lib/rails_config/options.rb:39:in `reload!'
	from /Users/joel/.rvm/gems/ruby-2.1.2@tonpsy/gems/rails_config-0.4.2/lib/rails_config.rb:32:in `load_files'
	from /Users/joel/.rvm/gems/ruby-2.1.2@tonpsy/gems/rails_config-0.4.2/lib/rails_config.rb:40:in `load_and_set_settings'
	from /Users/joel/.rvm/gems/ruby-2.1.2@tonpsy/gems/rails_config-0.4.2/lib/rails_config/integration/rails.rb:17:in `block in <class:Railtie>'
	from /Users/joel/.rvm/gems/ruby-2.1.2@tonpsy/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:36:in `call'
	from /Users/joel/.rvm/gems/ruby-2.1.2@tonpsy/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /Users/joel/.rvm/gems/ruby-2.1.2@tonpsy/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /Users/joel/.rvm/gems/ruby-2.1.2@tonpsy/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /Users/joel/.rvm/gems/ruby-2.1.2@tonpsy/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /Users/joel/.rvm/gems/ruby-2.1.2@tonpsy/gems/railties-4.1.9/lib/rails/application.rb:123:in `initialize'
	from /Users/joel/.rvm/gems/ruby-2.1.2@tonpsy/gems/railties-4.1.9/lib/rails/railtie.rb:171:in `new'
	from /Users/joel/.rvm/gems/ruby-2.1.2@tonpsy/gems/railties-4.1.9/lib/rails/railtie.rb:171:in `instance'
	from /Users/joel/.rvm/gems/ruby-2.1.2@tonpsy/gems/railties-4.1.9/lib/rails/application.rb:90:in `inherited'
```

**Comment by pkrefta** [comment]
You should sent your bug report to psych gem author - https://github.com/tenderlove/psych - this is about YAML parsing - not a rails_config issue.

**Comment by joel** [comment]
Ok Thanks

**Comment by joel** [comment]
https://github.com/tenderlove/psych/issues/228
