### ISSUE TITLE
"Use RbConfig instead of obsolete and deprecated Config." "Could not find generator config:install."

### ISSUE THREAD

**Issue by baburdick** [railsconfig/config#116]
```
$ rails g config:install
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/config-1.0.0.beta1/lib/generators/config/install_generator.rb:1:in `<top (required)>': Use RbConfig instead of obsolete and deprecated Config.
Could not find generator config:install.
```

**Comment by fredwu** [comment]
Are you on ruby 1.9.3 by any chance?

**Comment by fredwu** [comment]
Sorry ignore my last comment. I'm investigating...

**Comment by fredwu** [comment]
I've pushed `1.0.0.beta3` that should have this addressed (it's a workaround, I'm hoping no one is using ruby's corelib `Config` module).

**Comment by baburdick** [comment]
Hi @fredwu. Thanks for working on this and pushing an update. But I get the same generator error with beta 3.

And I'm seeing this when I update an app with beta 3 and try to run specs. (I get this error with beta 2, too):
```
NoMethodError: undefined method `setup' for RailsConfig:Module
/Users/some_guy/Code/Integra/some_application/config/initializers/rails_config.rb:1:in `<top (required)>'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:241:in `load'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:241:in `block in load'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:241:in `load'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/engine.rb:648:in `block in load_config_initializer'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/activesupport-4.1.12/lib/active_support/notifications.rb:161:in `instrument'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/engine.rb:647:in `load_config_initializer'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/engine.rb:611:in `each'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/engine.rb:611:in `block in <class:Engine>'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `instance_exec'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `run'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/initializable.rb:44:in `each'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/initializable.rb:44:in `tsort_each_child'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/initializable.rb:54:in `run_initializers'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/application.rb:300:in `initialize!'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `public_send'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `method_missing'
/Users/some_guy/Code/Integra/some_application/spec/dummy/config/environment.rb:5:in `<top (required)>'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `block in require'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/application.rb:276:in `require_environment!'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/application.rb:405:in `block in run_tasks_blocks'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/bin/ruby_executable_hooks:15:in `eval'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/bin/ruby_executable_hooks:15:in `<main>'
```
And this is my `config/initializers/rails_config.rb`:
```ruby
RailsConfig.setup do |config|
  config.const_name = "Settings"
end
```
I hope that gives you enough information to get to the bottom of this issue. Until then, I'm sticking with the last working release. So no rush here.

**Comment by fredwu** [comment]
The gem's been renamed to `Config`, so you should use `Config` instead of `RailsConfig` now. :)

**Comment by baburdick** [comment]
That doesn't appear to get me out of the woods:
```
NoMethodError: undefined method `setup' for RbConfig:Module
/Users/some_guy/Code/Integra/some_application/config/initializers/rails_config.rb:1:in `<top (required)>'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:241:in `load'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:241:in `block in load'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:241:in `load'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/engine.rb:648:in `block in load_config_initializer'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/activesupport-4.1.12/lib/active_support/notifications.rb:161:in `instrument'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/engine.rb:647:in `load_config_initializer'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/engine.rb:611:in `each'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/engine.rb:611:in `block in <class:Engine>'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `instance_exec'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `run'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/initializable.rb:44:in `each'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/initializable.rb:44:in `tsort_each_child'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/initializable.rb:54:in `run_initializers'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/application.rb:300:in `initialize!'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `public_send'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `method_missing'
/Users/some_guy/Code/Integra/some_application/spec/dummy/config/environment.rb:5:in `<top (required)>'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `block in require'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/application.rb:276:in `require_environment!'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/gems/railties-4.1.12/lib/rails/application.rb:405:in `block in run_tasks_blocks'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/bin/ruby_executable_hooks:15:in `eval'
/Users/some_guy/.rvm/gems/ruby-2.1.2@some_application/bin/ruby_executable_hooks:15:in `<main>'
```
Updated `config/initializers/rails_config.rb`:
```ruby
Config.setup do |config|
  config.const_name = "Settings"
end
```

**Comment by baburdick** [comment]
I get the same even if I use `config` v0.0.1 in the Gemfile and rename the initializer to `config/initializers/config.rb`.

**Comment by tarellel** [comment]
I have had the same issues since they have being making these beta changes and switching from rails_config to config, but in order to get the generator and application to actually load instead of just using `gem 'config'` I had to load it using the latest possible script available.

```ruby
# doesn't work
gem 'config'

# works
gem 'config', github: 'railsconfig/config'
```

I also had to make changed to the `config/initializers/config.rb` file you have to make sure the right module is being loaded.
```ruby
# old
RailsConfig.setup do |config|

# new
Config.setup do |config|
```

After making these slight changes everything started working great again. Best of luck to you!

**Comment by fredwu** [comment]
@tarellel Alternatively you could specify a beta version of the gem:

```ruby
gem 'config', '~> 1.0.0.beta3'
```

:)

**Comment by tomohiroakino** [comment]
67fef56 で対応済み
