### ISSUE TITLE
Undefined method 'delegate' when used with Padrino 0.14

### ISSUE THREAD

**Issue by fatmcgav** [railsconfig/config#184]
I'm trying to use `Config` with Padrino 0.14. 

I've added the entry to the Gemfile and added the `register Config` line to `app.rb`. 

However when I try and start Padrino, I get the following exception:
```
/Users/gavinw/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.15.0/lib/bundler/runtime.rb:85:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'config'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `delegate' for Config::Options:Class
Did you mean?  DelegateClass
Backtrace for gem load error is:
/Users/gavinw/.rvm/gems/ruby-2.3.1@padrino/gems/config-1.6.0/lib/config/options.rb:156:in `<class:Options>'
/Users/gavinw/.rvm/gems/ruby-2.3.1@padrino/gems/config-1.6.0/lib/config/options.rb:5:in `<module:Config>'
/Users/gavinw/.rvm/gems/ruby-2.3.1@padrino/gems/config-1.6.0/lib/config/options.rb:4:in `<top (required)>'
/Users/gavinw/.rvm/gems/ruby-2.3.1@padrino/gems/config-1.6.0/lib/config.rb:4:in `require'
/Users/gavinw/.rvm/gems/ruby-2.3.1@padrino/gems/config-1.6.0/lib/config.rb:4:in `<top (required)>'
/Users/gavinw/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.15.0/lib/bundler/runtime.rb:82:in `require'

```

Any ideas?

**Comment by yhatt** [comment]
I have met this error too. `#delegate` is the feature of ActiveSupport so config fails in not rails environment.

...but I'm using rails. Our project is loading config earlier than initializing rails, for using config together with encrypted secrets. It would raise same error in that timing because ActiveSupport have not loaded...

I'm trying to fix it in #185.
