### ISSUE TITLE
JSON error with resque and multi_json

### ISSUE THREAD

**Issue by jlecour** [railsconfig/config#26]
Hi,

In a Rails app, where I also use resque, multi_json, yajl alongside with rails_config, I get errors whenever I try to pass a RailsConfig::Options object to a Resque job.

The error Is like this :

````
LoadError (no such file to load -- json):
  activesupport (3.0.7) lib/active_support/dependencies.rb:239:in `require'
  activesupport (3.0.7) lib/active_support/dependencies.rb:239:in `require'
  activesupport (3.0.7) lib/active_support/dependencies.rb:225:in `load_dependency'
  activesupport (3.0.7) lib/active_support/dependencies.rb:596:in `new_constants_in'
  activesupport (3.0.7) lib/active_support/dependencies.rb:225:in `load_dependency'
  activesupport (3.0.7) lib/active_support/dependencies.rb:239:in `require'
  rails_config (0.2.3) lib/rails_config/options.rb:52:in `to_json'
  multi_json (1.0.3) lib/multi_json/engines/yajl.rb:14:in `encode'
  multi_json (1.0.3) lib/multi_json/engines/yajl.rb:14:in `encode'
  multi_json (1.0.3) lib/multi_json.rb:72:in `encode'
  resque (1.19.0) lib/resque/helpers.rb:22:in `encode'
  resque (1.19.0) lib/resque.rb:151:in `push'
  resque (1.19.0) lib/resque/job.rb:48:in `create'
  resque (1.19.0) lib/resque.rb:233:in `enqueue'
````

Thanks for any help

**Comment by pkuczynski** [comment]
Closing due lack of feedback...
